### ISSUE TITLE
Heroku application error

### ISSUE THREAD

**Issue by designeng** [SC5/cerebellum-urls#1]
[Heroku app](https://cerebellumurls.herokuapp.com/) does not work:

```
An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details.
```

**Comment by hoppula** [comment]
Thanks for notifying, sorry that I didn't have time until now to check this. MongoHQ's free plan had expired, I had to replace it with MongoLab. Latest version is up and running now.
